#These db properties are optional for H2 embedded database
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: testuser
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8005
  
megam:
  name: MEGAM
  email: teammegham@gmail.com
  security:
    salt: testkey
    encoder: bcrypt

logging:
  level:
    '[org.springframework.security]': debug
    '[com.megam.security.mgmauth]': debug